#!/usr/bin/env bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
. $DIR/sc-_common

load_prev
pane_id=$(tmux display-message -p '#{pane_id}')
[[ -s "$MDIR/$pane_id.convo" ]] && convo_id=$(cat "$MDIR/${pane_id}.convo")

while getopts ":c:" opt; do
  case $opt in
    c)
      convo_id="$OPTARG"
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      ;;
  esac
done
shift $((OPTIND -1))

if [[ -z "$convo_id" ]]; then
    echo "No conversation means no context to add"
    exit 1
fi 

echo -e "\nAdding to $convo_id"
{   echo "<most-recent-commands>"
    tmux capture-pane -t "${pane_id}" -p | grep -v '^$' | tail -5
    echo -e "</most-recent-commands>\n<output>"
    test -t 0 || cat;
    # This takes a potential file passed in sc-add and cats it
    [[ -r "$1" ]] && cat "$1" 
    echo "</output>"
} | ll "Acknowlege in 1 paragraph" | sd
